### ISSUE TITLE
xcaddy: command not found when building caddy

### ISSUE THREAD

**Issue by marcoippolito** [caddyserver/xcaddy#7] opened 2020-04-24 16:31 UTC
Following these indications: https://caddyserver.com/docs/install#build-from-source
in Ubuntu 18.04.4 Desktop I installed xcaddy

    go get -u github.com/caddyserver/xcaddy/cmd/xcaddy
    go: downloading github.com/caddyserver/xcaddy v0.1.2
    go: found github.com/caddyserver/xcaddy/cmd/xcaddy in github.com/caddyserver/xcaddy v0.1.2
    go: downloading github.com/Masterminds/semver v1.4.2
    go: downloading github.com/Masterminds/semver/v3 v3.1.0
    go: github.com/Masterminds/semver/v3 upgrade => v3.1.0

And tried to build caddy:

    (base) marco@pc01:~/golangMatters/caddy/cmd/caddy$ xcaddy build v2.0.0-rc.3 \
    > --with github.com/caddyserver/nginx-adapter
    xcaddy: command not found

How to solve the problem?
Marco

**Comment by mholt** [comment] 2020-04-24 16:33
Duplicate of #6 and #5 -- as usual with any commands, just make sure it is in your PATH and that it is executable.

**Closed by mholt** 2020-04-24 16:33 UTC

**Comment by marcoippolito** [comment] 2020-04-24 17:03
@mholt 

    (base) marco@pc01:~$ echo $PATH
    /home/marco/anaconda3/bin:/home/marco/anaconda3/condabin:/home/marco/.pyenv/plugins
    /pyenv-virtualenv/shims:/home/marco/.pyenv/shims:/home/marco/.pyenv/bin:/home/marco
    /.nvm/versions/node/v12.15.0/bin:/home/marco/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:
    /usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/marco/.local/bin:/usr/lib/go
    /bin:/home/marco/go/bin:/home/marco/emsdk-master:/home/marco/emsdk-master
    /node/12.9.1_64bit/bin:/home/marco/emsdk-master/upstream/emscripten

/home/marco/go/bin seems to be in the path

And it is executable:

    (base) marco@pc01:~/go/bin$ ls -lah
    total 48M
    drwxr-xr-x 2 marco marco 4,0K apr 24 18:12 .
    drwxr-xr-x 5 marco marco 4,0K feb 18 08:05 ..
    -rwxr-xr-x 1 marco marco  20M feb 18 11:48 fabric-ca-client
    -rwxr-xr-x 1 marco marco  23M feb 18 11:48 fabric-ca-server
    -rwxr-xr-x 1 marco marco 4,6M apr 24 18:12 xcaddy


    (base) marco@pc01:~/go/bin$ xcaddy
    2020/04/24 19:02:57 [ERROR] exec: "go": executable file not found in $PATH


nano .bashrc  :  

    export GOROOT=/usr/lib/go
    export GOPATH=$HOME/go
    export PATH=$PATH:$GOROOT/bin:$GOPATH/bin

**Comment by mholt** [comment] 2020-04-24 17:14
That's a different error now: `exec: "go": executable file not found in $PATH`

Make sure that the `go` command is in your PATH too.

**Comment by marcoippolito** [comment] 2020-04-25 09:02
@mholt 
Solved. Thank you

    (base) marco@pc01:~/golangMatters/caddy/cmd/caddy$ xcaddy build v2.0.0-rc.3 --with     github.com/caddyserver/nginx-adapter

    2020/04/25 10:59:25 [INFO] Temporary folder: /tmp/buildenv_2020-04-25-1059.757018517
    2020/04/25 10:59:25 [INFO] Writing main module: /tmp/buildenv_2020-04-25-1059.757018517    
    /main.go
    2020/04/25 10:59:25 [INFO] Initializing Go module
    2020/04/25 10:59:25 [INFO] exec (timeout=10s): /usr/local/go/bin/go mod init caddy 
    go: creating new go.mod: module caddy
     2020/04/25 10:59:25 [INFO] Pinning versions
      2020/04/25 10:59:25 [INFO] exec (timeout=5m0s): /usr/local/go/bin/go get -d -v

**Comment by tjhowse** [comment] 2022-08-19 05:20
In case you end up here trying to install xcaddy:

Make sure you have something like this in your ~/.bashrc:
```
export GOROOT=/usr/lib/go
export GOPATH=$HOME/go
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
```
And install caddy with:
```
go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
```
The docs say to use `go get -u github.com/caddyserver/xcaddy/cmd/xcaddy`, but that is no longer correct.

**Comment by mohammed90** [comment] 2022-08-19 14:58
> The docs say to use `go get -u github.com/caddyserver/xcaddy/cmd/xcaddy`, but that is no longer correct.

Which docs are you speaking of?? It's been saying `go install` for the past one and half years: https://github.com/caddyserver/xcaddy/commit/83655481bffa4ff2a6a2c811ab0d95478ef084ef

**Comment by tjhowse** [comment] 2022-08-20 04:53
This one: https://github.com/caddyserver/nginx-adapter/blob/master/README.md#install

PR to update it: https://github.com/caddyserver/nginx-adapter/pull/28

**Comment by mholt** [comment] 2022-08-20 05:06
(Thank you!)
