### ISSUE TITLE
xcaddy build v2.3.0 --with Unable to obtain the specified version

### ISSUE THREAD

**Issue by weew2** [caddyserver/xcaddy#59] opened 2021-04-21 09:55 UTC
Adding the --with component will invalidate the specified version. Can you help solve this problem?

**1. Instruction one**

[root@centos-s-2vcpu-4gb-sfo3-03 caddy]# xcaddy build v2.3.0 \
>     --with github.com/caddyserver/forwardproxy \
>     --with github.com/caddy-dns/cloudflare
2021/04/21 09:53:24 [INFO] Temporary folder: /tmp/buildenv_2021-04-21-0953.136560700
2021/04/21 09:53:24 [INFO] Writing main module: /tmp/buildenv_2021-04-21-0953.136560700/main.go
2021/04/21 09:53:24 [INFO] Initializing Go module
2021/04/21 09:53:24 [INFO] exec (timeout=10s): /usr/bin/go mod init caddy 
go: creating new go.mod: module caddy
2021/04/21 09:53:24 [INFO] Pinning versions
2021/04/21 09:53:24 [INFO] exec (timeout=0s): /usr/bin/go get -d -v github.com/caddyserver/caddy/v2@v2.3.0 
2021/04/21 09:53:25 [INFO] exec (timeout=0s): /usr/bin/go get -d -v github.com/caddyserver/forwardproxy 
go: github.com/caddyserver/forwardproxy upgrade => v0.0.0-20201205091008-b3a96fb34dbe
2021/04/21 09:53:26 [INFO] exec (timeout=0s): /usr/bin/go get -d -v github.com/caddy-dns/cloudflare 
go: github.com/caddy-dns/cloudflare upgrade => v0.0.0-20210401224357-964e47d3890e
2021/04/21 09:53:26 [INFO] Build environment ready
2021/04/21 09:53:26 [INFO] Building Caddy
2021/04/21 09:53:26 [INFO] exec (timeout=0s): /usr/bin/go mod tidy 
2021/04/21 09:53:27 [INFO] exec (timeout=0s): /usr/bin/go build -o /etc/caddy/caddy -ldflags -w -s -trimpath 
2021/04/21 09:53:30 [INFO] Build complete: ./caddy
2021/04/21 09:53:30 [INFO] Cleaning up temporary folder: /tmp/buildenv_2021-04-21-0953.136560700
[root@centos-s-2vcpu-4gb-sfo3-03 caddy]# ./caddy version
v2.4.0-beta.2 h1:DUaK4qtL3T0/gAm0fVVkHgcMN04r4zGpfPUZWHRR8QU=

**2. 1. Instruction two**
[root@centos-s-2vcpu-4gb-sfo3-03 caddy]# xcaddy build v2.3.0  
2021/04/21 09:54:21 [INFO] Temporary folder: /tmp/buildenv_2021-04-21-0954.549121710
2021/04/21 09:54:21 [INFO] Writing main module: /tmp/buildenv_2021-04-21-0954.549121710/main.go
2021/04/21 09:54:21 [INFO] Initializing Go module
2021/04/21 09:54:21 [INFO] exec (timeout=10s): /usr/bin/go mod init caddy 
go: creating new go.mod: module caddy
2021/04/21 09:54:21 [INFO] Pinning versions
2021/04/21 09:54:21 [INFO] exec (timeout=0s): /usr/bin/go get -d -v github.com/caddyserver/caddy/v2@v2.3.0 
2021/04/21 09:54:22 [INFO] Build environment ready
2021/04/21 09:54:22 [INFO] Building Caddy
2021/04/21 09:54:22 [INFO] exec (timeout=0s): /usr/bin/go mod tidy 
2021/04/21 09:54:23 [INFO] exec (timeout=0s): /usr/bin/go build -o /etc/caddy/caddy -ldflags -w -s -trimpath 
2021/04/21 09:54:26 [INFO] Build complete: ./caddy
2021/04/21 09:54:26 [INFO] Cleaning up temporary folder: /tmp/buildenv_2021-04-21-0954.549121710
[root@centos-s-2vcpu-4gb-sfo3-03 caddy]# ./caddy version
v2.3.0 h1:fnrqJLa3G5vfxcxmOH/+kJOcunPLhSBnjgIvjXV/QTA=

**Comment by mholt** [comment] 2021-04-21 22:47
Probably a duplicate of #54.

**Closed by mholt** 2021-04-21 22:47 UTC
