### ISSUE TITLE
Building with go 1.21 fails at quic-go step

### ISSUE THREAD

**Issue by plexxman** [caddyserver/xcaddy#151] opened 2023-08-17 17:17 UTC
**System:** Arch Linux 6.4.10-arch1-1
**Package information:**
- go 2:1.21.0-1 (from official repositories)
- xcaddy-bin 0.3.5-1 (from AUR)
- xcaddy 0.3.5 (binary from this repo releases)

With recent go's 1.21 update, xcaddy doesn't build a custom caddy version with modules and throws the following error related to quic-go (I assume by the logs). I tested both with AUR's package, and downloading the binary directly from this repo to be sure and both give the same error:

https://pastebin.com/5v1SMvWj

Reverting back to go 2:1.20.7-1 fixes the issue and xcaddy builds correctly a custom version of Caddy with modules. If you need more tests let me know.

PD.: Sorry for using pastebin but I had a weird issue while adding the log in a code block here.

**Comment by mholt** [comment] 2023-08-17 17:18
This is a known issue that is being fixed by Caddy v2.7.4 today.

(Go made a last-minute breaking change to new APIs which broke quic-go moments before release.)

**Comment by francislavoie** [comment] 2023-08-17 17:21
Duplicate of https://github.com/caddyserver/caddy/pull/5719

**Closed by francislavoie** 2023-08-17 17:21 UTC

**Comment by plexxman** [comment] 2023-08-17 17:26
Roger that, I'll stay in position then! Thanks for the quic😄 response.

**Comment by plexxman** [comment] 2023-08-17 19:57
I can confirm that it is fixed with Caddy 2.7.4, building perfectly with go 1.21.

**Comment by mholt** [comment] 2023-08-17 22:31
Thanks! That's good. :)
